import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillInstagram, AiFillGithub} from 'react-icons/ai'
import Image from "next/image";
import mitoru from "../public/mitoru.png";
import {useState} from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mitoru Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10">
        <section className="min-h-screen">
    	    <nav className="py-10 mb-12 flex justify-between">
           <h1 className="text-xl">Mitoru Portfolio</h1> 
           <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className=" bg-gradient-to-r from-cyan-500 to-sky-500 text-white px-4 py-2 rounded ml-8" href="#">Lebenslauf</a></li>
           </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-sky-500 font-medium">Mitoru Dev</h2>
            <h3 className="text-2xl py-2">Developer and designer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800"> This is text i need to change soon !</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillInstagram />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-cyan-500 rounded-full w-72 h-72 mt-20 overflow-hidden">
            <Image src={mitoru} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800"> 
              Since the beginning of my journey as a freelencer designer and developer, I've done remote work for 
              <span className="text-sky-500"> agencies </span> 
              consulted for 
              <span className="text-sky-500"> startups </span> 
              and collaborated with talanted people to create digital products for both business and consumer use. 
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
